---
title: "p8105_hw5_jys2136"
author: "Jocelyn Sun"
date: "11/17/2021"
output: github_document
---

```{r, setup, message = FALSE, echo = TRUE}

library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_bw()) + theme(axis.text.x = element_text(size = 9),
                              axis.text.y = element_text(size = 9),
                              legend.position = "bottom")

```

# Problem 1

```{r, homicide_df}

homicide_df = 
  read_csv("homicide-data.csv",  na = c("", "Unknown")) %>% 
  mutate(city_state = str_c(city, state),
         resolution = case_when(
           disposition == "Closed without arrest" ~ "unsolved",
           disposition == "Open/No arrest" ~ "unsolved",
           disposition == "Closed by arrest" ~ "solved"
         )) %>% 
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")

  


```

Focusing on Baltimore, MD
```{r, baltimore_df}

baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")


baltimore_summary =
  baltimore_df %>% 
  summarise(
    unsolved = sum(resolution == "unsolved"),
    n = n()
    )


baltimore_test = 
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n))


baltimore_test %>% 
  broom::tidy() %>% 
  knitr::kable()

```


```{r, prop_test_function}

prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>% 
      summarise(
        unsolved = sum(resolution == "unsolved"),
        n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
    )
  
  return(city_test)
  
}

# trying for another city 
homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function() %>% 
  broom::tidy() %>% 
  knitr::kable()

```


```{r, iteration}

results_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
    ) %>% 
    select(city_state, tidy_results) %>% 
    unnest(tidy_results) %>% 
    select(city_state, estimate, starts_with("conf"))

head(results_df) %>% 
  knitr::kable()

```


```{r}
results_df %>% 
  filter(city_state != "TulsaAL") %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +  
  theme(axis.text.x = element_text(size = 5, angle = 90, vjust = 0.5, hjust = 1))
  
``` 

# Problem 2

```{r}


longstudy_df = 
  tibble(path = list.files("./data", full.names = TRUE)) %>% 
  mutate(data = purrr::map(.x = path, ~read_csv(.x))) %>% 
  unnest(data) %>%
  separate(path, c("dot", "folder", "txt"), sep = "/")

```











